CSC-41 Implement main Lottery flow as an integration test script
finixio/crypto-luckyblock-smart-contracts pull request #8
Opened 2022-05-20 07:11 UTC by videjkk

Added 
        * LinkToken.sol - as a helper contract of LINK token
        * VRFCoordingatorMock.sol - mock of a VRF Coordinator contract
        * preprod.test.js - test whick cover all processes of lottery flow

2022-05-20 07:58 UTC, 0xYanush requested changes
add reverted tests, calling `adminOnly` functions from **not-admin** accounts as well, we are not covering only positive cases

2022-05-20 07:58 UTC, 0xYanush commented on hardhat.config.js
> -            accounts: [process.env.ADMIN_PRIVATE_KEY],
why would we remove this for testnet?

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +        ;[
add const instead of `;` ?

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +            endDate,
are those values changed during this test? if not — does this make sense to make them`const`?

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +                    charityPercentages[3]
spread please

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +                receipt.events[receipt.events.length - 1].args.winnerAddress
`const [winnerADdress, totalJackpotAmount] = receipt.events[receipt.events.length - 1].args` would work? try to avoid unnecessary code duplication. DRY

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +        it("Jackpot winner should be picked from users by owner", async function () {
misleading test description

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +            expect(winnerAddress).to.not.equal(ethers.constants.AddressZero)
check if winner address in array of users in lottery please

2022-05-20 07:58 UTC, 0xYanush commented on test/preprod.test.js
> +        })
is this specific to this `describe` or could be reused from global scope?

2022-05-20 09:48 UTC, videjkk commented on hardhat.config.js
> -            accounts: [process.env.ADMIN_PRIVATE_KEY],
there is a problem with running test when this .env variable is in array. In this case .env variable ADMIN_PRIVATE_KEY doesn't exist. but it tries to use it what is unnecessary.
![image](https://user-images.githubusercontent.com/86836604/169502182-0886d7ba-7778-4501-82b3-35080aecaaaf.png)

2022-05-20 09:49 UTC, videjkk commented on package.json
> +}
returned husky script

2022-05-20 09:54 UTC, videjkk commented on .gitignore
> +artifacts
deleted redundant artifacts
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/078e9870b6ce0aca65d5f4c8b229e998e8f3e4ef

2022-05-20 09:56 UTC, videjkk commented on test/preprod.test.js
> +                    charities[3],
Replaced arguments with spread
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/860e4d338c59ce762b207eade01fcf06d1e000c3

2022-05-20 10:05 UTC, videjkk commented on test/preprod.test.js
> +                    charityPercentages[3]
Replaced arguments with spread
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/commit/860e4d338c59ce762b207eade01fcf06d1e000c3

2022-05-20 10:08 UTC, videjkk commented on test/preprod.test.js
> +        ;[
added const and moved from before function because of scope of const
https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/abb8e86856a9660c75ea0d616445ad4057d95f4b

2022-05-20 10:10 UTC, videjkk commented on test/preprod.test.js
> +        it("Jackpot winner should be picked from users by owner", async function () {
changed test description to more clearly description 
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/cb1c889a147648d6bf77149d2fae5e9dd2052a23

2022-05-20 12:08 UTC, videjkk commented on test/preprod.test.js
> +        it("Jackpot winner should be picked from users by owner", async function () {
fixed this
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/3b1705ae1ce3539bb0cf1e5c4e8f350938ad5a8d

2022-05-20 12:13 UTC, videjkk commented on test/preprod.test.js
> +                receipt.events[receipt.events.length - 1].args.winnerAddress
added destruction 
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/6e19cb6d95de6c35771d62e0bf0b6c61e5f9eacf

2022-05-20 12:21 UTC, videjkk commented on test/preprod.test.js
> +        })
made LBlockLottery and LBlockLotteryAddress global
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/968770a32034cdea28e950d624217a26791a502a

2022-05-20 13:14 UTC, videjkk commented on test/preprod.test.js
> +            for (let usersIndex = 0; usersIndex < users.length; usersIndex++) {
decided to replace with Promise.all
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/bbc5cbc11659411fc4abb511dc6df459e2caf615

2022-05-20 13:15 UTC, videjkk commented on test/preprod.test.js
> +            expect(winnerAddress).to.not.equal(ethers.constants.AddressZero)
fixed
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/f55e155a90072fe280aa9568ff0ddbfac015ab89

2022-05-20 13:26 UTC, videjkk commented on test/preprod.test.js
> +            endDate,
There is no way to do this. If we move them upper test will be just skipped

2022-05-20 13:51 UTC, videjkk commented on test/preprod.test.js
> +})
added nftwinner test case and lottery pool
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/6e772daf32cb647c3c8267bcd9418276db7999da

2022-05-23 07:40 UTC, videjkk commented on hardhat.config.js
> -            accounts: [process.env.ADMIN_PRIVATE_KEY],
fixed this 
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/578c07a0727628bcbc58895af87bbde3ba0acb9a

2022-05-23 07:42 UTC, videjkk commented on hardhat.config.js
> -            accounts: [process.env.ADMIN_PRIVATE_KEY],
fixed
commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/d6634f7e4fcbb5123bf05327aca479daa8e0ce9c

2022-05-23 11:07 UTC, videjkk commented
@0xYanush 

- fixed package.json's tab-width commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/277d1fec20900ce26925ba6bccd3284ff02fbdab
- made variables as constants commit: https://github.com/finixio/crypto-luckyblock-smart-contracts/pull/8/commits/71703ddc126dbc20f18a211f103f96c43984c1c4

2022-05-23 12:20 UTC, 0xYanush approved these changes

2022-05-23 12:21 UTC, merged